[project]
name = "clip_saver"
version = "1.0.0"
description = "Process video streams with YOLO object detection and customizable callbacks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "lapx>=0.9.4",
    "supervision>=0.27.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "ultralytics>=8.4.6",
]

[dependency-groups]
dev = [
    "pytest>=9.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
